### ISSUE TITLE
Scheduler Exception

### ISSUE THREAD

**Issue by jakublipinski** [KlubJagiellonski/pola-backend#53]
```
2017-08-13 05:02:08.000
138 <190>1 2017-08-13T05:02:07.335602+00:00 app scheduler.1295 - - .Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/framework_django.py", line 909, in _nr_wrapper_BaseCommand_run_from_argv_
    return wrapped(*args, **kwargs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/api/function_trace.py", line 104, in literal_wrapper
    return wrapped(*args, **kwargs)
  File "/app/pola/management/commands/delete_rare_products.py", line 56, in handle
    [product_id])
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/app/.heroku/python/lib/python2.7/site-packages/newrelic-2.56.0.42/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
django.db.utils.IntegrityError: update or delete on table "product_product" violates foreign key constraint "ai_pics_aipic_product_id_45918407312df2b2_fk_product_product_id" on table "ai_pics_aipics"
```

**Comment by mik-laj** [comment]
Oj. Możesz zrobić hotfixa,  ale zaczynając pracę od starych commitow, zanim zacząłem aktualizację. Trzeba jeszcze trochę podnieść testy przed wrzuceniem aktualnego kodu na produkcję.
